name: navigation_drawer_challenge
description: Navigation Drawer Challenge

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/jewellery/
    - assets/images/leather_goods/
    - assets/images/perfumes/
    - assets/images/skincare/
    - assets/images/wrist_watches/

  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/chanel.png
